VkNet/Model/Post.cs

Идентификатор создателя записи в группе или паблике (тот, кто фактически
ее написал)

К записи добавлено поле CreatedBy

---

VkNet/Model/Message.cs
VkNet/VkApi.cs

Время последнего вызова метода (lastInvokeTime) вынесено в паблик, добавлено кол-во непрочитанных сообщений #72

Мелкие добавления

---

VkNet/Categories/MessagesCategory.cs

Исправлена ошибка NullReferenceException в Messages.GetHistory.

Исправлена ошибка NullReferenceException

---

VkNet.Tests/Categories/GroupsCategoryTest.cs
VkNet/Categories/GroupsCategory.cs

Исправил метод groups.search (Вместо параметра fields должен был быть future)

Задача 66. Исправил метод groups.search

---

VkNet.Tests/Categories/GroupsCategoryTest.cs

Очень извиняюсь, забыл за константы в тестах

Задача 66. Забыл за константы в тестах

---

VkNet.Tests/Categories/MessagesCategoryTest.cs
VkNet/Categories/MessagesCategory.cs
VkNet/Model/Attachments/Link.cs
VkNet/Model/Message.cs

Поправил метод messages.getHistory
messages.getById
messages.getDialogs
messages.search
Реализовал методы: messages.getLongPollHistory,
messages.deleteChatPhoto,
messages.setChatPhoto,
messages.markAsImportant,
Исправил метод messages.search (падало с ошибкой),
Переход к без знаковым переменным где это нужно
Остался нетронутым только метод send

#127. Дополнение к messages

---

VkNet/Model/ApiAuthParams.cs
VkNet/Utils/Browser.cs
VkNet/Utils/IBrowser.cs
VkNet/Utils/WebCall.cs
VkNet/VkApi.cs

Почти всегда при использовании прокси, VK требует ввод каптчи. Но в целом работает.

Поддержка прокси (без авторизации).

---

VkNet/Model/RequestParams/Photo/PhotoEditParams.cs

Add param:
*CaptchaSid
*CaptchaKet
Caption urlDecode

PhotoEditParams

---

VkNet/Enums/Filters/UsersFields.cs

исправления фильтра UsersFields

---

VkNet/Model/FriendList.cs
VkNet/VkApi.cs

- Пофиксил ошибку со списками друзей (ид списков не правильно парсился)
- Добавил публичную переменную Token, только чтение, получение из переменной AccessToken (имхо, в некоторых случаях необходим токен (например сохранить токен, чтобы не авторизовываться по новой (очень удобно при 2FA)))

Fix and Token field

---

VkNet/Utils/Cookies.cs

Подключил System.Collections для Hashtable и убрал System.Collection.Generic (теперь не используется)

Отредактировал using

---

VkNet/Categories/AccountCategory.cs
VkNet/Categories/AppsCategory.cs
VkNet/Categories/NewsFeedCategory.cs
VkNet/Categories/PagesCategory.cs
VkNet/Categories/PhotoCategory.cs
VkNet/Categories/StatsCategory.cs
VkNet/Categories/UsersCategory.cs
VkNet/Categories/VideoCategory.cs
VkNet/Categories/WallCategory.cs
VkNet/VkApi.cs

- Исправлены вызовы методов с параметром skipAuthorization
- Исправлен метод GetApiUrl

Исправлены вызовы методов с параметром skipAuthorization

---

VkNet/Model/RequestParams/Users/UsersGetNearbyParams.cs

- Тип параметров Latitude и Longtitude изменен с long на double(теперь можно использовать дробные координаты). 
- Изменен код преобразования Latitude и Longtitude в строку(VK API выбрасывает ошибку 100 при передаче ей дробного числа с запятой-разделителем, нужна точка)

Изменение типа Longtitude и Latitude в UsersGetNearbyParams

---

VkNet/Utils/AntiCaptcha/ICaptchaSolver.cs
VkNet/Utils/VkParameters.cs
VkNet/VkApi.cs
VkNet/VkNet.csproj

- Добавлен интерфейс универсального решателя капчи `ICatchaSolver`.
- Изменен код метода `VkApi.Call(methodName, parameters, skipAuthorization)`.
- Изменен код (добавлена "заглушка") для метода `VkApi.Authorize(appId, emailOrPhone, password, settings, code, captchaSid, captchaKey, host, port)`.
- Изменен конструктор класса `VkApi`, добавлен необязательный параметр `ICatchaSolver`, сохранена обратная совместимость.
- В класс `VkApi` добавлено свойство `MaxCaptchaRecognitionCount`, задающее максимальное число  неудачных, идущих подряд попыток распознавания капчи, после чего попытки распознать капчу будут прекращены.

Добавлена поддержка решателя капчи

---

VkNet/Utils/VkResponseToManualEnumCastsGenerator1.cs

- Фикс метода Friend.Delete (#238)

Фикс метода Friend.Delete (#238)

---

VkNet/Categories/PagesCategory.cs

Fixed Pages.Save method

---

VkNet/Model/RequestParams/Board/BoardCreateCommentParams.cs
VkNet/Model/User.cs

- Add Captcha parameters to BoardCreateCommentParams
- Small fix user.BirthdayVisibility 
.

Add Captcha parameters to BoardCreateCommentParams

---

VkNet/Categories/BoardCategory.cs
VkNet/Model/RequestParams/Board/BoardDeleteCommentParams.cs
VkNet/Utils/ModelToVkParametrsCastGenerator.cs
VkNet/VkNet.csproj

- добавлен метод Board.DeleteComment

Add Board.DeleteComment function

---

VkNet/Model/AudioAlbum.cs

- Заменил название поля "album_Id" на "id" в JSON - согласно документации VK.API

Change field "album_Id" to "id" - according to the VK.API documentation

---

VkNet/Categories/BoardCategory.cs
VkNet/Model/RequestParams/Board/BoardAddTopicParams.cs
VkNet/Model/RequestParams/Board/BoardEditTopicParams.cs
VkNet/Model/RequestParams/Board/BoardTopicParams.cs
VkNet/Utils/ModelToVkParametrsCastGenerator.cs
VkNet/VkNet.csproj

- Добавил Board.AddTopic
- Добавил Board.EditTopic
- Добавил Board.FixTopic
- Добавил Board.UnFixTopic
- Добавил Board.CloseTopic
- Добавил Board.OpenTopic 
- Добавил Board.DeleteTopic
- Несколько исправлений ошибок в описании методов

Add addTopic, deleteTopic, editTopic, openTopic, closeTopic, fixTopic,UnFixTopic to the Board

---

VkNet/Categories/BoardCategory.cs
VkNet/Model/Group/Group.cs
VkNet/Model/RequestParams/Board/BoardCommentParams.cs
VkNet/Model/RequestParams/Board/BoardEditCommentParams.cs
VkNet/Utils/ModelToVkParametrsCastGenerator.cs
VkNet/VkNet.csproj

- Добавил Board.EditComment
- Добавил Board.RestoreComment

Add EditComment, RestoreComment to the Board

---

VkNet/Model/ApiAuthParams.cs
VkNet/Utils/Browser.cs
VkNet/Utils/IBrowser.cs
VkNet/Utils/WebCall.cs
VkNet/VkApi.cs

Реализована работа через прокси с авторизацией (#190) 
- Добавлены свойства proxyLogin и proxyPassword для работы через прокси с авторизацией в ApiAuthParams.
- Добавлены аргументы proxyLogin и proxyPassword для методов передающих данные о прокси-сервере.
P.S. возможно лучше выделить параметры прокси-сервера в отдельную структуру?
P.P.S. это мой первый пул-реквест. Нуждаюсь в конструктивной критике.

Поддержка прокси с авторизацией.

---

VkNet/Categories/AppsCategory.cs
VkNet/Categories/BoardCategory.cs
VkNet/Categories/FriendsCategory.cs
VkNet/Categories/GroupsCategory.cs
VkNet/Categories/LikesCategory.cs
VkNet/Categories/PhotoCategory.cs
VkNet/Categories/UsersCategory.cs
VkNet/Categories/WallCategory.cs
VkNet/Model/RequestParams/Messages/MessagesGetParams.cs
VkNet/VkApi.cs

-  	Изменение типа переменной VkApi.RequestsPerSecond (#292)
-      Добавлены аргумент skipAuthorization для методов, которые можно вызывать без access_token (#291)

Фикс #291 и #292, добавление аргумента SkipAuthorization

---

VkNet/Model/Career.cs
VkNet/Model/User.cs

- Поле Career в User сделано коллекцией
- поле From в Career сделано nullable

fix Vk.Users.Search(Fields = ProfileFields.Career)

---

VkNet.Tests/BaseTest.cs
VkNet/Categories/BoardCategory.cs
VkNet/VkApi.cs

- Поправил BaseTest - иначе не собирался
- описание <param name="skipAuthorization" в Board
- привел сборку к собираемому виду.

несколько маленьких изменений

---

VkNet/Model/Career.cs

- Фикс проблемы с Career (#293)
p.s. критика приветствуется

Фикс Career(#293)

---

VkNet/VkApi.cs

исправлен баг при частых запросах

---

VkNet/Categories/LikesCategory.cs

исправлена возвращаемая коллекция ID лайков при Get запросе

---

VkNet/Utils/DataAnnotations.cs

As per https://blog.jetbrains.com/dotnet/2015/08/12/how-to-use-jetbrains-annotations-to-improve-resharper-inspections/

Change JetBrains.Annotations to internal

---

VkNet/Categories/WallCategory.cs

Отключена проверка авторизации для метода wall.get

wall.get authorization fix

---

VkNet/Categories/MessagesCategory.cs

Фикс проверки наличия attachment при отправке личного сообщения.
До фикса при отсутствии поля message не давал отправлять вложения.

Qwertyo1 message.send.patch

---

VkNet.userprefs
VkNet/Utils/VkResponseToModelCastsGenerator.tt
VkNet/VkNet.csproj

- Исправлена сборка на Unix'ах.

Исправлена сборка на Unix'ах.

---

VkNet.UWP/VkApi.cs

- Исправлен доступ к методу get у свойства RequestsPerSecond

Fixed RequestsPerSecond prop

---

VkNet.UWP/Model/Attachments/Attachment.cs

- Добавлена поддержка товаров в постах (#367)

Добавлена поддержка товаров в постах

---

VkNet.UWP/Model/ApiAuthParams.cs
VkNet.UWP/Utils/Browser.cs
VkNet.UWP/Utils/IBrowser.cs
VkNet.UWP/Utils/WebProxy.cs
VkNet.UWP/VkApi.cs

Список изменений
- В ApiAuthParams добавлены параметры для авторизации с помощью токена, полученного извне. При этом при заполнении параметров Login, Password, ApplicationId, Settings в будущем доступна функция RefreshToken.
Также теперь доступна работа через прокси сервер при авторизации с помощью токена, полученного извне.
- В IBrowser задание прокси сервера реализовано через свойство
- Исправлена ошибка в функции GetProxy (https://github.com/vknet/vk/issues/385)
Реализовано аналогично конструктору оригинального WebProxy (https://github.com/dotnet/corefx/blob/master/src/System.Net.WebProxy/src/System/Net/WebProxy.cs)

Модифицирована функция авторизации, исправлена ошибка в WebProxy

---

VkNet.UWP/Enums/Filters/ProfileFields.cs

- Добавил поле FollowersCount в ProfileFields

Фикс для #401

---

VkNet.UWP/Model/Place.cs

- Широта и долгота должны иметь тип double, они неверно округлялись до int

Latitude and Longitude should have a double type

---

VkNet.UWP/Categories/Obsolete/FriendsCategory.Obsolete.cs
VkNet.UWP/Model/RequestParams/Friends/FriendsGetRequestsParams.cs

- FriendsGetRequestsParams  получил параметр NeedViewed

FriendsGetRequestsParams: NeedViewed

---

VkNet.UWP/Utils/Browser.cs
VkNet.UWP/Utils/IBrowser.cs
VkNet.UWP/VkApi.cs

- Функция Validate в основном классе VkApi
- Функция Validate в интерфейсе IBrowser и его реализации Browser

Добавил обход ошибки валидации: https://vk.com/dev/need_validation

---

VkNet.Shared.Tests/Categories/PhotosCategoryTest.cs
VkNet.UWP/Categories/PhotoCategory.cs

- Добавлена реализация методов https://vk.com/dev/photos.getOwnerCoverPhotoUploadServer и https://vk.com/dev/photos.saveOwnerCoverPhoto

Implementation getOwnerCoverPhotoUploadServer and saveOwnerCoverPhoto

---

VkNet.UWP.Tests/Enum/Filters/MultivaluedFilterTest.cs
VkNet.UWP/Enums/Filters/ProfileFields.cs

- Добавлен CropPhoto в ProfileFields

Add CropPhoto field

---

VkNet/Model/RequestParams/Wall/WallEditParams.cs

При редактировании поста может вылететь капча. Добавил параметры капчи в WallEditParams.

WallEditParams Captcha

---

VkNet.Tests/Utils/UtilitiesTests.cs
VkNet/Utils/JsonConverter/VkCollectionJsonConverter.cs

- Добавлена реализация конвертации VkCollection в JSON - формат

Fix VkCollectionJsonConverter

---

categories/groups/getMembers.md

- Изменение 1
Исправлен пример вызова метода Groups.GetMembers
Исправлено получение общего кол-ва участников группы

Groups.GetMembers

---

VkNet.Tests/Utils/VkErrorsTest.cs
VkNet/Exception/ErrorExecutingCodeException.cs
VkNet/Exception/ImpossibleToCompileCodeException.cs
VkNet/Utils/ErrorCode.cs
VkNet/Utils/VkErrors.cs

- Добавлены отсутствующие ошибки 12, 13

Error 12, 13 

---

VkNet/Model/NewsSearchResult.cs

Add PostId response
- Изменение 1

Add PostId response

---

VkNet/Abstractions/Async/INotesCategoryAsync.cs
VkNet/Abstractions/INotesCategory.cs
VkNet/Categories/Async/NotesCategoryAsync.cs
VkNet/Categories/NotesCategory.cs
VkNet/Model/CommentNote.cs
VkNet/Model/RequestParams/Notes/NotesAddParams.cs
VkNet/Model/RequestParams/Notes/NotesCreateCommentParams.cs
VkNet/Model/RequestParams/Notes/NotesDeleteCommentParams.cs
VkNet/Model/RequestParams/Notes/NotesEditCommentParams.cs
VkNet/Model/RequestParams/Notes/NotesEditParams.cs
VkNet/Model/RequestParams/Notes/NotesGetByIdParams.cs
VkNet/Model/RequestParams/Notes/NotesGetCommentParams.cs
VkNet/Model/RequestParams/Notes/NotesGetParams.cs
VkNet/Model/RequestParams/Notes/NotesRestoreCommentParams.cs
VkNet/VkApi.cs
VkNet/VkNet.csproj

- Добавлены методы и классы для работы с заметками

Issue #525  Добавлены методы и классы для работы с заметками

---

README.md

Критическая ошибка

---

VkNet/Model/User.cs

-К свойствам добавлены JsonProperty
- Изменение 1

Исправление модели User

---

VkNet.Tests/Categories/Story/StoriesGetTests.cs
VkNet.Tests/Enum/SafetyEnums/SafetyEnumTests.cs
VkNet/Abstractions/Category/Async/IStoriesCategoryAsync.cs
VkNet/Abstractions/Category/IStoriesCategory.cs
VkNet/Categories/Async/StoriesCategoryAsync.cs
VkNet/Categories/StoriesCategory.cs
VkNet/Enums/SafetyEnums/StoryLinkText.cs
VkNet/Enums/SafetyEnums/StoryObjectState.cs
VkNet/Model/RequestParams/Stories/GetPhotoUploadServerParams.cs
VkNet/Model/StoryResult.cs
VkNet/Model/StoryServerUrl.cs
VkNet/Model/StoryStatsObject.cs
VkNet/Model/StoryStatsResult.cs

- Добавлены методы и классы для работы с Историями.

Добавлены методы и классы для работы с Историями

---

VkNet/Model/Attachments/Message.cs
VkNet/Model/Attachments/Photo.cs

- Исправлена модель Сообщения.
- Добавлены отсутствующие поля у Photo (photo_50, photo_100, photo_200) для Message.Action.Photo

Исправлена модель Сообщения

---

VkNet/Abstractions/Category/IOrdersCategory.cs
VkNet/Categories/OrdersCategory.cs
VkNet/Enums/SubscriptionStatus.cs
VkNet/Model/SubscriptionItem.cs
VkNet/Model/VotesAmount.cs

add description for orders' methods

---

categories/groups/isMember.md

Обновил пример реализации.
- Изменение 1

Обновил пример

---

index.md

Добавил ссылку на GetLongPollServer
- Изменение 1

Добавил ссылку на GetLongPollServer

---

VkNet/Model/Coordinates.cs
VkNet/Model/Place.cs
VkNet/Utils/VkResponse.cs

-  Исправлено получение координат для Geo - теперь 2 варианта - 1 для стены (когда приходит одной строкой {"широта долгота"}( был до этого), 2 вариант с прикрепления geo - в виде  {"latitude":(double), "longitude":(double)} (добавлен)
- Изменено в Place поля Country и City на string (вк апи отдает в таком виде) [https://vk.com/dev/objects/geo](https://vk.com/dev/objects/geo)

Исправлено получение гео координат
